# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""generate image tool."""

import asyncio
from dataclasses import asdict
from logging import Logger

from mcp.server.fastmcp import FastMCP
from schemas import (
  ImageGenerationRequest,
  ImageMetadata,
  ResizeImageRequest,
)
from services.agents.factory import AgentFactory
from services.image_service import generate_image_service
from utils.image import convert_image_to_part


def register_generate_images_tool(
  mcp: FastMCP, logger: Logger, bucket_name: str
) -> None:
  """Register the generate image tool on the provided MCP server."""

  @mcp.tool()
  async def generate_images(
    requests: list[ImageGenerationRequest],
  ) -> list[ImageMetadata]:
    """
    Generates images on the provided visual description or Edits reference images by adding characters or modifying it based on a visual description using the Nano Banana model. Supports parallel generation of multiple requests.
    This tool can be used to generate first-frame images for video generation.

    Args:
      requests:  A list of ImageGenerationRequest objects.
                Each object contains:
                - visual_description: A text prompt from the user describing the desired image.
                - aspect_ratio: Aspect ratio of output image (e.g., '16:9', '9:16', '1:1'). Default to 16:9
                - reference_images (Optional): Reference images.

    Returns:
      A list of edited image metadata that contains:
        - gcs_uri: GCS URI of the edited image.
        - authenticated_url: URL of the edited image where user can view.
        - image_description: Description of what the edited image looks like.

    Response: The response must explicitly direct the user to the `authenticated_url` to view each edited images.
    """  # noqa: E501

    logger.info("Invoking generate_images tool.")
    logger.info(f"Received {len(requests)} image editing requests.")

    edited_image_uris: list[ImageMetadata] = await asyncio.gather(
      *[
        generate_image_service(
          **asdict(req),
          output_gcs_uri=f"gs://{bucket_name}/generated_images",
        )
        for req in requests
      ]
    )

    logger.info(f"Done generating images: {edited_image_uris}")
    return edited_image_uris

  @mcp.tool()
  async def resize_image(
    requests: list[ResizeImageRequest],
  ) -> list[ImageMetadata]:
    """
    Resize an image by cropping or extending to specified aspect ratio using the Nano Banana model. Supports parallel generation of multiple requests.
    Use this tool when the user wants to change the aspect ratio of input images that is not generated by Nano Banana model.

    Args:
      requests:  A list of ResizeImageRequest objects.
                Each object contains:
                - reference_image: GCS URI of the reference image to resize.
                - aspect_ratio: Aspect ratio of output image (e.g., '16:9', '9:16', '1:1'). Default to 16:9

    Returns:
      A list of edited image metadata that contains:
        - gcs_uri: GCS URI of the edited image.
        - authenticated_url: URL of the edited image where user can view.
        - image_description: Description of what the edited image looks like.

    Response: The response must explicitly direct the user to the `authenticated_url` to view each edited images.
    """  # noqa: E501

    logger.info("Invoking resize_image tool.")
    logger.info(f"Received {len(requests)} resize image requests.")

    async def resize_single_image(req: ResizeImageRequest) -> ImageMetadata:
      """Resize a single image based on the request."""
      generative_cropping_agent = AgentFactory.create_image_agent(
        agent_name="generative_cropping",
      )
      prompt = f"Crop the Image to a new aspect ratio {req.aspect_ratio}, precisely maintaining absolute fidelity to the original content, style, and environmental properties."  # noqa: E501
      image_urls = await generative_cropping_agent.generate_images(
        contents=[prompt, convert_image_to_part(image=req.reference_image)],
        aspect_ratio=req.aspect_ratio,
        output_gcs_uri=f"gs://{bucket_name}/generated_images",
      )
      return await ImageMetadata.create(image_urls[0])

    resized_images: list[ImageMetadata] = await asyncio.gather(
      *[resize_single_image(req) for req in requests]
    )

    logger.info(f"Done resizing images: {resized_images}")
    return resized_images
