# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Base class for Image generation model."""

from typing import Any

from google.genai import types
from schemas.media import RawMediaItem
from shared.config import config
from tenacity import retry, stop_after_attempt, wait_exponential
from utils import log, storage

from services.agents import base_agent

logger = log.get_logger()


class GeminiImageAgent(base_agent.BaseAgent):
  """Gemini image generation/editing agent."""

  def __init__(
    self,
    agent_name: str = "Gemini image generation model",
    model_name: str = config.get(
      "gemini_image_model", "gemini-2.5-flash-image"
    ),
    model_config: dict[str, Any] | None = None,
    automatic_function_calling: bool = False,
  ):
    super().__init__(
      agent_name=agent_name,
      model_name=model_name,
      model_config=model_config or {},
      automatic_function_calling=automatic_function_calling,
    )

  @retry(
    wait=wait_exponential(min=5, max=60, multiplier=2),
    stop=stop_after_attempt(5),
  )
  async def generate_images(
    self,
    contents: types.ContentUnionDict,
    aspect_ratio: str = "16:9",
    output_dir: str | None = None,
    output_gcs_uri: str | None = None,
  ) -> list[str]:
    """Generate image(s) from a text prompt."""
    logger.info(f"Invoking {self.agent_name} for text-to-image generation.")
    logger.debug(self._build_request_log(contents))
    try:
      self.model_config.response_modalities = ["IMAGE"]
      self.model_config.image_config = types.ImageConfig(
        aspect_ratio=aspect_ratio
      )
      response: types.GenerateContentResponse = (
        await self.genai_client.aio.models.generate_content(
          model=self.model_name,
          contents=contents,
          config=self.model_config,
        )
      )
      images = self._collect_inline_images(response)
      assert images, "No images were generated by the model."
    except Exception as err:
      logger.error(err)
      raise err
    logger.debug(self._build_response_log(response, len(images)))

    return storage.save_media_batch(
      images,
      output_dir,
      output_gcs_uri,
      file_prefix="image",
    )

  def _collect_inline_images(
    self, response: types.GenerateContentResponse
  ) -> list[RawMediaItem]:
    """Extract inline image payloads from the response."""
    images: list[RawMediaItem] = []
    for candidate in response.candidates or []:
      if not candidate.content or not candidate.content.parts:
        continue
      for part in candidate.content.parts or []:
        inline_data = getattr(part, "inline_data", None)
        if inline_data and getattr(inline_data, "data", None):
          images.append(
            RawMediaItem(
              mime_type="image/png",
              data=inline_data.data,
            )
          )
    return images

  def _build_response_log(
    self, response: types.GenerateContentResponse, image_count: int
  ) -> str:
    text_response = response.text or "No text response received."
    return f"""
    Image Generation Response:
    -----------------------------------------------------------
    Text:
    {text_response}
    -----------------------------------------------------------
    Inline images count: {image_count}
    -----------------------------------------------------------
    """
